### ISSUE TITLE
Close several UI-related issues

### ISSUE THREAD

**Issue by pandres95** [PoetriIsCode/CLI#8]
- [x] [Signup Seems Complicated (internal)](https://gitlab.com/poetri/clients/cli/issues/1)
- [x] [Simplify init process (internal)](https://gitlab.com/poetri/clients/cli/issues/2)
- [x] [Clarify difference between "Function ID and Function Name" (internal)](https://gitlab.com/poetri/clients/cli/issues/3)
